### ISSUE TITLE
Add basic usage docs

### ISSUE THREAD

**Issue by theetrain** [Hugos68/svelte-maskerize#12]
Congratulations on your package! When I go to the linked Alpine docs I see usage as `x-mask` attributes, though I'm guessing this library is meant to use `use:`.

Please provide a basic example of how to use this library, as well as a list of exported masks.

**Comment by Hugos68** [comment]
Thanks! That sounds like a good (and required) idea, will add the API usage + example in the readme.

**Comment by Hugos68** [comment]
@theetrain I updated the readme, please let me know if this is sufficient, ill close it then.

**Comment by theetrain** [comment]
Very nice, thank you!
