### ISSUE TITLE
Use the pattern attribute of html to make the action progressively enhanced

### ISSUE THREAD

**Issue by KevsRepos** [Hugos68/svelte-maskerize#7]
HTML input elements have a `pattern` attribute which allows specifying a regex which will be used by the browser to validate the input value.

I propose to let the action use the value of the `pattern` attribute to make the input progressively enhanced. When javascript or the action fails, the user still has information about what the input should look like.

**Comment by Hugos68** [comment]
I can see where you are coming from although I doubt how useful this will be when thinking more about this, if a user doesn't have javascript the action won't run and thus won't be able to set the pattern attribute

**Comment by theetrain** [comment]
I see this more as a nice-to-have. Since the core motivation is to implement Alpine's masks, that makes this more of a formatting library than a validation one. Consumers need to perform server-side validation anyway, and that may be out of scope for svelte-maskify.

**Comment by Hugos68** [comment]
Closing this as been made clear that this is out of scope for svelte-maskify.
